### ISSUE TITLE
CLImageProcessingUtil#convertYUVToBitmap竖屏处理图片方向是错的

### ISSUE THREAD

**Issue by wsdydeni** [microink/CLCameraXConverter#1]
https://blog.csdn.net/mozushixin_1/article/details/123892476
这篇文档的工具类最牛

**Comment by microink** [comment]
> https://blog.csdn.net/mozushixin_1/article/details/123892476 这篇文档的工具类最牛

1. 旋转是将旋转角度传入到工具内部的，这篇文档也是，如果发现传入了正确角度，旋转却错误可以发出关键代码用以查看问题
2. YUV转换当然是可以的，最初我的实现也是基于此，可以查看博客里面的YUV转换工具https://blog.csdn.net/microink/article/details/143837800
3. 工具的目的是提高速度，减少计算量，你提到的文章是全量转换，浪费了一些视野外的计算量，当然转换的原理都是一样的

**Comment by microink** [comment]
另外再补充一句，正向的竖屏，要获取正确的图像，需要传入90度的旋转角度，因为Camera输出图像是横向。

**Comment by microink** [comment]
> https://blog.csdn.net/mozushixin_1/article/details/123892476 这篇文档的工具类最牛

1. 旋转是将旋转角度传入到工具内部的，这篇文档也是，如果发现传入了正确角度，旋转却错误可以发出关键代码用以查看问题
2. YUV转换当然是可以的，最初我的实现也是基于此，可以查看博客里面的YUV转换工具https://blog.csdn.net/microink/article/details/143837800
3. 工具的目的是提高速度，减少计算量，在Java层转换速度慢和内存抖动无法避免，所以才有后来的YUV转换方式

**Comment by wsdydeni** [comment]
> > https://blog.csdn.net/mozushixin_1/article/details/123892476 这篇文档的工具类最牛
> 
> 1. 旋转是将旋转角度传入到工具内部的，这篇文档也是，如果发现传入了正确角度，旋转却错误可以发出关键代码用以查看问题
> 2. YUV转换当然是可以的，最初我的实现也是基于此，可以查看博客里面的YUV转换工具https://blog.csdn.net/microink/article/details/143837800
> 3. 工具的目的是提高速度，减少计算量，在Java层转换速度慢和内存抖动无法避免，所以才有后来的YUV转换方式

CameraX1.4.0的图像方向是错的，现在默认图片是横向，-90°旋转才是正常。

**Comment by wsdydeni** [comment]
> > > https://blog.csdn.net/mozushixin_1/article/details/123892476 这篇文档的工具类最牛
> > 
> > 
> > 
> > 1. 旋转是将旋转角度传入到工具内部的，这篇文档也是，如果发现传入了正确角度，旋转却错误可以发出关键代码用以查看问题
> > 2. YUV转换当然是可以的，最初我的实现也是基于此，可以查看博客里面的YUV转换工具https://blog.csdn.net/microink/article/details/143837800
> > 3. 工具的目的是提高速度，减少计算量，在Java层转换速度慢和内存抖动无法避免，所以才有后来的YUV转换方式
> 
> CameraX1.4.0的图像方向是错的，现在默认图片是横向，-90°旋转才是正常。

CameraX的工具类在国内这么多系统下很多手机不生效的，源码里面甚至有TODO，没有正确的给JEPG设置EXIF。

**Comment by microink** [comment]
> > > > https://blog.csdn.net/mozushixin_1/article/details/123892476 这篇文档的工具类最牛
> > > 
> > > 
> > > 
> > > 1. 旋转是将旋转角度传入到工具内部的，这篇文档也是，如果发现传入了正确角度，旋转却错误可以发出关键代码用以查看问题
> > > 2. YUV转换当然是可以的，最初我的实现也是基于此，可以查看博客里面的YUV转换工具https://blog.csdn.net/microink/article/details/143837800
> > > 3. 工具的目的是提高速度，减少计算量，在Java层转换速度慢和内存抖动无法避免，所以才有后来的YUV转换方式
> > 
> > 
> > CameraX1.4.0的图像方向是错的，现在默认图片是横向，-90°旋转才是正常。
> 
> CameraX的工具类在国内这么多系统下很多手机不生效的，源码里面甚至有TODO，没有正确的给JEPG设置EXIF。

JPEG等输出图像是通过拍照通道来处理，而不是ImageAnalysis，这是一款ImageAnalysis的工具库。
CLImageProcessingUtil是进行YUV到RGB的转换，不涉及图像旋转，如果需要旋转需要自行处理。
华为手机测试在拍照时确实旋转是有问题的，需要根据官方文档处理的角度尝试处理。

**Comment by wsdydeni** [comment]
> > > > > https://blog.csdn.net/mozushixin_1/article/details/123892476 这篇文档的工具类最牛
> > > > 
> > > > 
> > > > 
> > > > 1. 旋转是将旋转角度传入到工具内部的，这篇文档也是，如果发现传入了正确角度，旋转却错误可以发出关键代码用以查看问题
> > > > 2. YUV转换当然是可以的，最初我的实现也是基于此，可以查看博客里面的YUV转换工具https://blog.csdn.net/microink/article/details/143837800
> > > > 3. 工具的目的是提高速度，减少计算量，在Java层转换速度慢和内存抖动无法避免，所以才有后来的YUV转换方式
> > > 
> > > 
> > > CameraX1.4.0的图像方向是错的，现在默认图片是横向，-90°旋转才是正常。
> > 
> > 
> > CameraX的工具类在国内这么多系统下很多手机不生效的，源码里面甚至有TODO，没有正确的给JEPG设置EXIF。
> 
> JPEG等输出图像是通过拍照通道来处理，而不是ImageAnalysis，这是一款ImageAnalysis的工具库。 CLImageProcessingUtil是进行YUV到RGB的转换，不涉及图像旋转，如果需要旋转需要自行处理。 华为手机测试在拍照时确实旋转是有问题的，需要根据官方文档处理的角度尝试处理。

哈哈，我处理好了，大佬。这个库总体是非常优秀的，大佬加油，完善这个库。
